name: Java CI

on:
  push:
    branches: 
      - main  # or your default branch, e.g., 'master'
  pull_request:
    branches: 
      - main  # or your default branch, e.g., 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (update to Java 23)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Changed to Java 23
          distribution: 'temurin'  # Try 'adoptopenjdk' if needed

      # Step 3: Set up Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # Step 4: Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Run tests
      - name: Run Tests
        run: ./gradlew test